baseURL = "https://tridentvisualmedia.com"
languageCode = "en"
title = "Trident Visual Media"
theme = "congo"
defaultContentLanguage = "en"
enableRobotsTXT = true
[pagination]
  pagerSize = 10

[taxonomies]
  series = "series"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true