backend:
  name: github
  repo: renderpro-code/tridentvisualmedia
  branch: main
  base_url: "https://tridentvisualmedia.com"
  auth_endpoint: "api/auth"

media_folder: static/images
public_folder: /images

collections:
  - name: books
    label: Books
    folder: content/series
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Series
        name: series
        widget: select
        options:
          - miller-crime-thriller
          - echoes-of-the-void
      - label: Publication Date
        name: date
        widget: datetime
      - label: Cover Image
        name: cover
        widget: image
        required: false
      - label: Blurb
        name: description
        widget: text
      - label: Amazon URL
        name: amazon_url
        widget: string
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown

  - name: blog
    label: Blog Posts
    folder: content/blog
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Description
        name: description
        widget: text
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown
